name: Add API Schema
 description: Request adding a new API schema source
 title: "Add API schema: <provider>"
 body:
   - type: input
     id: provider
     attributes:
       label: Provider ID
       placeholder: example.com
   - type: input
     id: schema
     attributes:
       label: OpenAPI URL
       placeholder: https://api.example.com/openapi.json
   - type: textarea
     id: notes
     attributes:
       label: Notes
